main: elevador.c modbus.c modbus.h crc16.h crc16.c utils_raspberry.h utils_raspberry.c pid.h pid.c fila.h fila.c
	cc -Wall elevador.c modbus.c modbus.h crc16.h crc16.c utils_raspberry.h utils_raspberry.c pid.h pid.c fila.h fila.c control_lcd_16x2.c control_lcd_16x2.h -lwiringPi -lpthread -o elevador
