cruzamento: cruzamento.c utils_file.h utils_file.c utils_sockets.h utils_sockets.c semaforos.h semaforos.c utils_raspberry.c utils_raspberry.h sensores.h sensores.c
	cc -Wall cruzamento.c utils_file.h utils_file.c utils_sockets.h utils_sockets.c semaforos.h semaforos.c sensores.h sensores.c utils_raspberry.h utils_raspberry.c -lwiringPi -lpthread -o cruzamento 
